services:
  - type: web
    name: info-permission-server
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DATA_DIR
        value: /var/data
    disk:
      name: app-data
      mountPath: /var/data
      sizeGB: 1
